import Head from "next/head";
import { Inter } from "next/font/google";
import Accordion from "./accordion";
import { GetStaticProps } from "next";
import CommentData from "./components/interface";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }: CommentData) {
  return (
    <>
      <Head>
        <title>Accordion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Accordion data={data} />
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch(`https://dummyjson.com/comments`);
  const comments = await res.json();
  const data = comments.comments;
  return {
    props: {
      data,
    },
  };
};
